safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Ak Sabapathy"
description: "Welcome to my blog!"
baseurl: ""
url: "http://aksaba.github.io" # replace by your site's url
twitter_username: aksabapathy
github_username:  aksaba # (your name)
accent: "#f7f7e6" # accent color for blog column
remote_theme: christianezeani/panthera-jekyll
author: "Karthik Sabapathy"
address: "Chennai, India"
email: ""

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
